### ISSUE TITLE
Too hard to read the contents.

### ISSUE THREAD

**Issue by nithin-84** [coronasafe/ml.coronasafe#8]
Its better to keep the words like " മിഡിൽ ഈസ്റ്റ് റെസ്പിറേറ്ററി സിൻഡ്രോം" , "എം. ഈ. ആർ. എസ്-സി. ഒ. വി" in english.

**Comment by bodhish** [comment]
Can you send a PR?

**Comment by nithin-84** [comment]
> Can you send a PR?

sure.
